"""
CCP FR22 — 3-Level Anti-Draft Intelligence Models (DEP-PROTO-013)

Pydantic v2 models for the Anti-Draft Calibration Protocol.
Every compiled SKILL.md receives a 3-level contrastive fence injected
before any positive instruction reaches the generation agent.

Spec reference: FR22_Anti_Draft_Intelligence_Tech_Spec.md
  §3 — Architecture Traceability (DEP-ENG-021[M3_UNDENIABLE], DEP-ENG-004)
  §4 — Stage 1: Level 1 Construction (Frozen Anchor — Block A Invariant Load)
  §4 — Stage 2: Level 2 Generation (Mode & M3 Synthesis)
  §4 — Stage 3: Level 3 Injection (Negative Space Load)
  §4 — Stage 4: Critic Subagent Enforcement Gate
  §5 — Primary Output Schema (anti_draft_deliberation_log.json)

Critical constraints:
  - Frozen Anchor Mandate: Level 1 MUST use a frozen, low-capability model
    (e.g., gpt-3.5-turbo). The primary model NEVER generates its own anchor.
  - Absolute First Load Order (M3 Mandate): DEP-ENG-004 (Level 3) MUST be
    loaded FIRST — before any positive instruction.
  - Gate PC-03: L3 array must contain >= 15 contrastive strings.
    Violation triggers L3_INSUFFICIENT_DEPTH halt.
  - Critic Gate: violations >= 2 → full purge + Pass 3 regenerate.
               violations == 1 → targeted section rewrite.
               violations == 0 → pass payload.

ADR-01: coach_id scopes all operations per tenant isolation mandate.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field

# ─── Constants ────────────────────────────────────────────────────────────────

FROZEN_ANCHOR_MODEL: str = "gpt-3.5-turbo"
"""The frozen low-capability model used for Level 1 anchor generation.
Spec §4 Stage 1: 'intentionally generated by a frozen, low-capability model
to permanently lock the statistical centroid.'"""

L3_MINIMUM_DEPTH_THRESHOLD: int = 15
"""Gate PC-03: Minimum contrastive strings required in DEP-ENG-004.
Spec §4 Stage 3: 'array must contain count >= 15 exact contrastive strings.'"""

L1_MINIMUM_PROSE_SENTENCES: int = 3
"""Block C validation: Level 1 must contain >= 3 sentences of literal prose.
Spec §4 Stage 1 Failure Condition: 'Level 1 contains descriptions instead
of concrete written prose.'"""

CRITIC_FULL_PURGE_THRESHOLD: int = 2
"""Spec §4 Stage 4: IF violations >= 2 → complete regeneration (Pass 3)."""


# ─── Enumerations ─────────────────────────────────────────────────────────────

class AntiDraftLevel(str, Enum):
    """The three levels of the Anti-Draft Calibration Protocol.

    Spec §2: Level 1 = Archetype (statistical centroid),
             Level 2 = Mode/Belief (M3_UNDENIABLE),
             Level 3 = Voice (coach's cognitive drift patterns DEP-ENG-004).
    """
    LEVEL_1_ARCHETYPE = "LEVEL_1_ARCHETYPE"
    LEVEL_2_MODE_BELIEF = "LEVEL_2_MODE_BELIEF"
    LEVEL_3_VOICE = "LEVEL_3_VOICE"


class ViolationType(str, Enum):
    """Violation categories detected by the Critic Subagent.

    Spec §4 Stage 4:
      Level 1 breach → generic cliché detected.
      Level 2 breach → mode payload delivery failed or M3 catered to.
      Level 3 breach → forbidden string found.
    """
    LEVEL_1_GENERIC_CLICHE = "LEVEL_1_GENERIC_CLICHE"
    LEVEL_2_MODE_FAILURE = "LEVEL_2_MODE_FAILURE"
    LEVEL_2_M3_CATERED_TO = "LEVEL_2_M3_CATERED_TO"
    LEVEL_3_PROFESSIONAL_HEDGE = "LEVEL_3_PROFESSIONAL_HEDGE"
    LEVEL_3_FORBIDDEN_STRING = "LEVEL_3_FORBIDDEN_STRING"
    LEVEL_3_STRUCTURAL_SHORTCUT = "LEVEL_3_STRUCTURAL_SHORTCUT"


class CriticPass(str, Enum):
    """Which generation pass the Critic is evaluating."""
    PASS_1_INITIAL = "PASS_1"
    PASS_2_POST_REWRITE = "PASS_2"
    PASS_3_FULL_REGENERATE = "PASS_3"


class CriticVerdict(str, Enum):
    """Outcome of Critic Subagent evaluation.

    Spec §4 Stage 4:
      PASS_GENERATION_PAYLOAD → 0 violations.
      TARGETED_SECTION_REWRITE → exactly 1 violation.
      FULL_PURGE_REGENERATE → violations >= 2.
    """
    PASS_GENERATION_PAYLOAD = "PASS_GENERATION_PAYLOAD"
    TARGETED_SECTION_REWRITE = "TARGETED_SECTION_REWRITE"
    FULL_PURGE_REGENERATE = "FULL_PURGE_REGENERATE"


class Level2Mode(str, Enum):
    """The psychological routing mode for Level 2 synthesis.

    Spec §4 Stage 2: Processing Mode vs Escape Mode have distinct
    mode-failure scenarios.
    """
    PROCESSING = "Processing"
    ESCAPE = "Escape"
    DISCOVERY = "Discovery"
    SOCIAL = "Social"


class AntiDraftHaltReason(str, Enum):
    """Hard halt reasons for the Anti-Draft pipeline.

    Spec §6 Backward Compatibility:
      L3 and L1 absence are FATAL HALTs — no fallback.
      M3 absence degrades gracefully.
    """
    L3_INSUFFICIENT_DEPTH = "L3_INSUFFICIENT_DEPTH"
    L1_ABSENT = "L1_ABSENT"
    L1_ABSTRACT_DESCRIPTION = "L1_ABSTRACT_DESCRIPTION"
    DEP_ENG_004_ABSENT = "DEP_ENG_004_ABSENT"
    DAG_VIOLATION = "DAG_VIOLATION"
    CONTEXT_WINDOW_TRUNCATION = "CONTEXT_WINDOW_TRUNCATION"


class L2DegradationReason(str, Enum):
    """Non-fatal degradation codes for Level 2.

    Spec §6: 'If DEP-ENG-021[M3_UNDENIABLE] is absent → CRAL_DEGRADED
    scenario. Falls back to generic mode_failure without specific belief anchor.'
    """
    M3_ABSENT_L2_DEGRADED = "M3_ABSENT_L2_DEGRADED"
    CRAL_DEGRADED = "CRAL_DEGRADED"


class FinalSemanticDistanceStatus(str, Enum):
    """Output of the full Anti-Draft fence evaluation."""
    MAXIMIZED = "MAXIMIZED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


# ─── Level 1: Frozen Anchor Block ─────────────────────────────────────────────

class Level1FrozenAnchor(BaseModel):
    """Level 1 Anti-Draft Block — Archetype Centroid Anchor.

    Spec §4 Stage 1: 'archetype's AI Cliché anchor is intentionally generated
    by a frozen, low-capability model (e.g., gpt-3.5-turbo) to permanently
    lock the statistical centroid.'

    Required subsections per spec §4 Stage 1 Step 2:
      [Statistical Centroid Prose Example]
      [Mechanism Failure Diagnosis]
      [Resolution Failure Diagnosis]
      [Semantic Distance Instruction]
    """

    frozen_model_used: str = Field(
        default=FROZEN_ANCHOR_MODEL,
        description="Spec: MUST be a frozen low-capability model, NEVER the primary model.",
    )
    statistical_centroid_prose: str = Field(
        default="",
        description=(
            "3-5 sentences of terrible AI cliché — concrete written prose. "
            "Spec §3 Technical Decision 1: NEVER a list of rules to avoid. "
            "Must be literal bad text acting as a negative semantic anchor."
        ),
    )
    mechanism_failure_diagnosis: str = Field(
        default="",
        description="Why generic AI fails mechanistically for this archetype.",
    )
    resolution_failure_diagnosis: str = Field(
        default="",
        description="Why generic AI's resolution structure fails emotionally.",
    )
    semantic_distance_instruction: str = Field(
        default="",
        description="Explicit instruction to maximise vector distance from this centroid.",
    )
    archetype_id: str = Field(
        default="",
        description="Archetype this anchor is locked to.",
    )
    receipt_hash: str = Field(
        default="",
        description="Cryptographic hash written to Receipt Chain Guard (DEP-ENG-041).",
    )

    def is_valid_prose(self) -> bool:
        """AC1 guard: Level 1 must be concrete prose, not abstract descriptions.

        Spec §8 AC1: Submitting Level 1 as 'Avoid clichés and generic tone.'
        results in immediate Block C Compilation failure.
        """
        prose = self.statistical_centroid_prose.strip()
        if not prose:
            return False
        # Count sentences (split on . ! ?)
        import re
        sentences = [s.strip() for s in re.split(r"[.!?]+", prose) if s.strip()]
        return len(sentences) >= L1_MINIMUM_PROSE_SENTENCES

    def has_all_subsections(self) -> bool:
        """Spec §4 Stage 1 Step 2: All 4 subsections must be populated."""
        return all([
            bool(self.statistical_centroid_prose.strip()),
            bool(self.mechanism_failure_diagnosis.strip()),
            bool(self.resolution_failure_diagnosis.strip()),
            bool(self.semantic_distance_instruction.strip()),
        ])


# ─── Level 2: Mode & M3 Synthesis Block ────────────────────────────────────────

class Level2ModeBelief(BaseModel):
    """Level 2 Anti-Draft Block — Mode-Specific + M3_UNDENIABLE Synthesis.

    Spec §4 Stage 2: Combines DEP-ENG-016 (Psychological Brief Mode) with
    DEP-ENG-021[M3_UNDENIABLE] to construct the mode-failure scenario.

    Backward Compatibility (Spec §6):
      If M3_UNDENIABLE is absent → falls back to generic mode_failure.
      Logs M3_ABSENT_L2_DEGRADED. NOT a pipeline halt.
    """

    routing_mode: Level2Mode = Field(
        ...,
        description="DEP-ENG-016: Psychological routing mode.",
    )
    m3_belief_text: Optional[str] = Field(
        default=None,
        description="DEP-ENG-021[M3_UNDENIABLE]: The specific wrong belief the audience holds.",
    )
    mode_failure_scenario: str = Field(
        default="",
        description=(
            "Spec §4 Stage 2 Step 2: "
            "Processing Mode → 'mechanism correct but payload unearned'. "
            "Escape Mode → 'vehicle mirrors audience L3 pain domain'."
        ),
    )
    m3_subversion_command: Optional[str] = Field(
        default=None,
        description=(
            "Spec §4 Stage 2 Step 3: "
            "'The draft assumes the audience believes [M3 belief]. "
            "You must actively tear this assumption down.'"
        ),
    )
    degradation_reason: Optional[L2DegradationReason] = Field(
        default=None,
        description="Set when M3 is absent (CRAL_DEGRADED scenario).",
    )
    receipt_hash: str = Field(default="")

    @property
    def is_degraded(self) -> bool:
        """True when M3 was absent and Level 2 falls back to generic mode."""
        return self.degradation_reason is not None


# ─── Level 3: Negative Space Injection Block ───────────────────────────────────

class ForbiddenVocabularyBlock(BaseModel):
    """Level 3 Anti-Draft Block — Forbidden Vocabulary from DEP-ENG-004.

    Spec §4 Stage 3: 'Explicitly load DEP-ENG-004 FIRST.'
    Gate PC-03: count >= 15 exact contrastive strings.
    If thin (< 15 items) → L3_INSUFFICIENT_DEPTH halt.

    Four vectors extracted from DEP-ENG-004 (NegativeSpaceObject):
      1. Cognitive Load Drift Patterns (sentence openers)
      2. Professional Register Hedges (latinate substitutions)
      3. Performed vs. Lived Vocabulary (aspirational — FORBIDDEN-PERFORMED)
      4. Structural Shortcuts (e.g., summary bullets)
    """

    dep_eng_004_hash: str = Field(
        default="",
        description="SHA-256 hash of the DEP-ENG-004 object used — guarantees immutability.",
    )
    cognitive_load_drift_patterns: list[str] = Field(
        default_factory=list,
        description="Sentence openers used when coach is cognitively uncertain.",
    )
    professional_register_hedges: list[str] = Field(
        default_factory=list,
        description="Latinate/corporate substitution vocabulary FORBIDDEN.",
    )
    performed_vocabulary: list[str] = Field(
        default_factory=list,
        description="Aspirational language marked FORBIDDEN-PERFORMED.",
    )
    structural_shortcuts: list[str] = Field(
        default_factory=list,
        description="Structural macro-shortcuts (e.g., summary bullets) FORBIDDEN.",
    )
    forbidden_strings_flat: list[str] = Field(
        default_factory=list,
        description="Flat union of all four vectors — the FORBIDDEN STRINGS list.",
    )
    total_count: int = Field(
        default=0,
        description="Total forbidden strings — must be >= 15 for Gate PC-03.",
    )
    receipt_hash: str = Field(default="")
    loaded_first: bool = Field(
        default=False,
        description=(
            "Spec §8 AC3: DEP-ENG-004 Level 3 'Forbidden Strings' MUST appear "
            "sequentially BEFORE DEP-ENG-003 Authentic Voice targets in the final "
            "SKILL.md text stream sent to the LLM."
        ),
    )

    def passes_depth_gate(self) -> bool:
        """Gate PC-03: L3 Minimum Depth Threshold.
        Spec §4 Stage 3: 'count >= 15 exact contrastive strings.'"""
        return self.total_count >= L3_MINIMUM_DEPTH_THRESHOLD


# ─── Critic Report ─────────────────────────────────────────────────────────────

class CriticViolation(BaseModel):
    """A single violation detected by the Critic Subagent.

    Spec §4 Stage 4: Each level scored independently.
    """

    violation_type: ViolationType
    level: AntiDraftLevel
    offending_text_excerpt: str = Field(
        default="",
        description="Excerpt from draft_v1.md that triggered the violation.",
    )
    forbidden_string_matched: Optional[str] = Field(
        default=None,
        description="The exact forbidden string matched (Level 3 violations).",
    )


class CriticReport(BaseModel):
    """Output of the Critic Subagent evaluation (Pass 2).

    Spec §4 Stage 4:
      - violations >= 2 → FULL_PURGE_REGENERATE (Pass 3).
      - violations == 1 → TARGETED_SECTION_REWRITE.
      - violations == 0 → PASS_GENERATION_PAYLOAD.

    AC4: 'Critic successfully spots 3 violations → halts, purges draft,
    restarts generation with critic_report.json as context.'
    Failure Example: Critic just logs them as warnings and passes the flawed script.
    """

    pass_evaluated: CriticPass = Field(
        default=CriticPass.PASS_1_INITIAL,
    )
    violations: list[CriticViolation] = Field(
        default_factory=list,
    )
    violation_count: int = Field(
        default=0,
        description="Total violation count — drives the verdict decision.",
    )
    verdict: CriticVerdict = Field(
        default=CriticVerdict.PASS_GENERATION_PAYLOAD,
    )
    targeted_rewrite_triggered: bool = Field(
        default=False,
    )
    full_purge_triggered: bool = Field(
        default=False,
    )
    context_window_truncated: bool = Field(
        default=False,
        description="Spec §4 Stage 4 Failure Condition: critic failed due to truncation.",
    )
    receipt_hash: str = Field(default="")

    def model_post_init(self, __context: Any) -> None:
        """Auto-derive verdict, violation_count, and triggered flags."""
        self.violation_count = len(self.violations)
        if self.violation_count >= CRITIC_FULL_PURGE_THRESHOLD:
            self.verdict = CriticVerdict.FULL_PURGE_REGENERATE
            self.full_purge_triggered = True
            self.targeted_rewrite_triggered = False
        elif self.violation_count == 1:
            self.verdict = CriticVerdict.TARGETED_SECTION_REWRITE
            self.targeted_rewrite_triggered = True
            self.full_purge_triggered = False
        else:
            self.verdict = CriticVerdict.PASS_GENERATION_PAYLOAD
            self.targeted_rewrite_triggered = False
            self.full_purge_triggered = False


# ─── Validation Pass Summary ────────────────────────────────────────────────────

class AntiDraftValidationPass(BaseModel):
    """Tracks which levels were successfully loaded/generated.

    Spec §5 Output Schema: anti_draft_deliberation_log.json
    'validation_pass' block.
    """

    level_1_archetype_loaded: bool = Field(default=False)
    level_2_mode_generated: bool = Field(default=False)
    level_3_negative_space_loaded: bool = Field(default=False)

    def all_loaded(self) -> bool:
        """All three levels must be present for a full anti-draft fence."""
        return (
            self.level_1_archetype_loaded
            and self.level_2_mode_generated
            and self.level_3_negative_space_loaded
        )


# ─── Deliberation Log (Primary Output) ─────────────────────────────────────────

class AntiDraftDeliberationLog(BaseModel):
    """Primary output schema for DEP-PROTO-013 execution metadata.

    Written alongside the Final Script as anti_draft_deliberation_log.json.
    Spec §5: Full schema including receipt_chain_hash, validation_pass,
    critic_evaluation, and final_semantic_distance_status.

    ADR-01: coach_id scopes the log for tenant isolation.
    """

    compilation_request_id: str = Field(
        ...,
        description="Unique compilation request identifier.",
    )
    coach_id: str = Field(
        ..., min_length=3, max_length=3,
        description="ADR-01 tenant isolation — 3-char coach acronym.",
    )
    receipt_chain_hash: str = Field(
        default="",
        description="Spec §5: Cryptographic hash from Receipt Chain Guard.",
    )
    validation_pass: AntiDraftValidationPass = Field(
        default_factory=AntiDraftValidationPass,
    )
    level_1_block: Optional[Level1FrozenAnchor] = Field(
        default=None,
        description="The frozen anchor block. None means FATAL HALT.",
    )
    level_2_block: Optional[Level2ModeBelief] = Field(
        default=None,
        description="Mode+M3 synthesis. None means FATAL HALT (unless degraded).",
    )
    level_3_block: Optional[ForbiddenVocabularyBlock] = Field(
        default=None,
        description="Forbidden strings block. None means FATAL HALT.",
    )
    critic_evaluation: Optional[CriticReport] = Field(
        default=None,
        description="Critic subagent report — populated after Pass 1.",
    )
    deliberation_override: bool = Field(
        default=False,
        description="True when supervisor manually overrides a failed check.",
    )
    final_semantic_distance_status: FinalSemanticDistanceStatus = Field(
        default=FinalSemanticDistanceStatus.FAILED,
    )
    halt_reason: Optional[AntiDraftHaltReason] = Field(
        default=None,
        description="Non-None if the pipeline halted at any stage.",
    )
    halted: bool = Field(
        default=False,
        description="True if a fatal halt was triggered.",
    )
    l2_degradation_reason: Optional[L2DegradationReason] = Field(
        default=None,
        description="Set when Level 2 runs in degraded mode (M3 absent).",
    )

    def model_post_init(self, __context: Any) -> None:
        """Auto-derive halted and final_semantic_distance_status."""
        self.halted = self.halt_reason is not None
        if not self.halted and self.validation_pass.all_loaded():
            critic = self.critic_evaluation
            if critic and critic.violation_count == 0:
                self.final_semantic_distance_status = FinalSemanticDistanceStatus.MAXIMIZED
            elif critic and critic.violation_count == 1:
                self.final_semantic_distance_status = FinalSemanticDistanceStatus.PARTIAL
            elif self.validation_pass.level_2_mode_generated and (
                self.level_2_block and self.level_2_block.is_degraded
            ):
                self.final_semantic_distance_status = FinalSemanticDistanceStatus.PARTIAL
