const express = require('express');
const { Canvas, fetchImage } = require('skia-canvas');

const app = express();
app.use(express.json({ limit: '50mb' }));

// MOCK Pretext typography measurement bridge
app.post('/typography/measure', (req, res) => {
    const { text_elements, safe_zone } = req.body;
    
    // In production, @chenglou/pretext would be loaded, text paths extracted,
    // and binary search layout iteration executed to match safe_zone limits.
    
    // Mock response simulating a successful layout matching AC2
    res.json({
        is_overset: false,
        measurements: {
            "headline": {
                "element_id": "headline",
                "optimal_font_size": 48.5,
                "bounding_box": {"x": 54.0, "y": 80.0, "w": 486.0, "h": 172.0},
                "line_count": 3,
                "line_breaks": [4, 9, 14],
                "line_widths": [478.0, 462.0, 312.0],
                "shrink_wrap_width": 478.0,
                "annotation_coordinates": {}
            }
        }
    });
});

// Skia Canvas Composition Engine
app.post('/render/compose', async (req, res) => {
    const { layers, canvas: canvasDims } = req.body;
    
    const canvas = new Canvas(canvasDims.width || 1080, canvasDims.height || 1350);
    const ctx = canvas.getContext('2d');
    
    try {
        // Z-order is managed by input array ordering from backend
        for (const layer of layers) {
            if (layer.type === 'gradient_background') {
                const grad = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
                const stops = layer.params.stops || ['#000000', '#ffffff'];
                stops.forEach((c, idx) => grad.addColorStop(idx / (stops.length - 1), c));
                ctx.fillStyle = grad;
                ctx.fillRect(0, 0, canvas.width, canvas.height);
            }
            else if (layer.type === 'image') {
                if (layer.src && layer.src.startsWith('http')) {
                    const img = await fetchImage(layer.src);
                    ctx.globalCompositeOperation = layer.params?.blendMode || 'source-over';
                    ctx.drawImage(img, layer.bbox[0], layer.bbox[1], layer.bbox[2], layer.bbox[3]);
                    ctx.globalCompositeOperation = 'source-over'; // reset
                }
            }
            else if (layer.type === 'text') {
                ctx.font = `${layer.weight} ${layer.size}px ${layer.font}`;
                ctx.fillStyle = layer.color;
                // CPH-4 Clip path handling would be pre-calculated polygon masks mapped via ctx.clip()
                ctx.fillText(layer.content, layer.bbox[0], layer.bbox[1] + layer.size);
            }
            else if (layer.type === 'rough_rectangle') {
                // Skia drawPath implementation for SVG path string generated by Rough.js on backend 
                ctx.strokeStyle = layer.params?.color || '#cc0000';
                ctx.lineWidth = 4;
                ctx.strokeRect(layer.bbox[0], layer.bbox[1], layer.bbox[2], layer.bbox[3]);
            }
            // Add perspective_warp, depth_occlusion handlers
        }

        const buffer = await canvas.toBuffer('webp', { quality: 0.95 });
        // Return base64 for simplicity; prod uploads direct to R2
        res.json({
            status: "success",
            format: "webp",
            data: buffer.toString('base64')
        });

    } catch (e) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

const port = process.env.PORT || 4000;
app.listen(port, () => {
    console.log(`Skia Sidecar listening on port ${port}`);
});
