"""
CCP Photo Deck Sync
Task 4.11 — Manages coach photos with usage tracking and Sovereign Image Rule.

When a coach uploads a photo:
  - Assign PHOT Asset ID
  - Upload to Supabase Storage
  - Track usage count
  - Enforce Sovereign Image Rule (block AI-generated coach imagery)
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

from src.ccp.core.asset_id import AssetIDGenerator, AssetType
from src.ccp.core.receipt_chain import ReceiptChain
from src.ccp.services.notion_sync import NotionSync


class PhotoDeckSync:
    """Manage coach photo deck with usage tracking."""

    MAX_USAGE_BEFORE_OVERUSED = 5
    SOVEREIGN_IMAGE_KEYWORDS = [
        "ai generated", "generated by ai", "midjourney", "dall-e",
        "stable diffusion", "artificial", "deepfake",
    ]

    def __init__(self, coach_acronym: str):
        self.coach_acronym = coach_acronym.upper()
        self.notion = NotionSync(coach_acronym=self.coach_acronym)
        self.asset_gen = AssetIDGenerator(coach_acronym=self.coach_acronym)
        self.receipt_chain = ReceiptChain(coach_acronym=self.coach_acronym)

    async def register_photo(
        self,
        database_id: str,
        photo_name: str,
        storage_url: str,
        tags: list[str] = None,
        source_description: str = "",
    ) -> dict:
        """Register a new photo in the Photo Deck.

        Args:
            database_id: Notion Photo Deck database ID
            photo_name: Display name for the photo
            storage_url: Supabase Storage URL
            tags: Photo tags (Portrait, Action, etc.)
            source_description: How the photo was taken (for Sovereign Image check)

        Returns:
            Created Notion page data

        Raises:
            ValueError: If the image violates the Sovereign Image Rule
        """
        # Sovereign Image Rule check
        if self._is_ai_generated(source_description):
            self.receipt_chain.log(
                agent_id="photo_deck",
                action="sovereign_image_block",
                output_summary=f"BLOCKED: AI-generated image rejected: {photo_name}",
                decision="rejected",
            )
            raise ValueError(
                "🚫 Sovereign Image Rule: AI-generated coach imagery is not allowed. "
                "Only authentic photos of the coach are accepted."
            )

        # Generate Asset ID
        asset_id = self.asset_gen.generate(AssetType.PHOTO)

        # Build properties
        properties = {
            "Name": {"title": [{"text": {"content": photo_name}}]},
            "Asset ID": {"rich_text": [{"text": {"content": asset_id}}]},
            "Usage Count": {"number": 0},
            "Status": {"select": {"name": "Available"}},
            "Storage URL": {"url": storage_url},
        }

        if tags:
            properties["Tags"] = {
                "multi_select": [{"name": t} for t in tags]
            }

        result = await self.notion.create_page(database_id, properties)

        self.receipt_chain.log(
            agent_id="photo_deck",
            action="register_photo",
            asset_id=asset_id,
            output_summary=f"Registered: {photo_name} ({asset_id})",
            decision="registered",
            metadata={"storage_url": storage_url, "tags": tags or []},
        )

        return result

    async def record_usage(self, page_id: str, current_usage: int) -> dict:
        """Increment usage count and update status if overused."""
        new_count = current_usage + 1
        status = "Overused" if new_count > self.MAX_USAGE_BEFORE_OVERUSED else "Available"

        return await self.notion.update_page(page_id, {
            "Usage Count": {"number": new_count},
            "Status": {"select": {"name": status}},
        })

    async def get_available_photos(self, database_id: str) -> list[dict]:
        """Get all available (non-overused) photos."""
        return await self.notion.query_database(
            database_id,
            filter_obj={
                "property": "Status",
                "select": {"equals": "Available"},
            },
            sorts=[{"property": "Usage Count", "direction": "ascending"}],
        )

    def _is_ai_generated(self, description: str) -> bool:
        """Check if a photo description suggests AI generation."""
        description_lower = description.lower()
        return any(kw in description_lower for kw in self.SOVEREIGN_IMAGE_KEYWORDS)
