"""
CCP Step 5 — Psych Routing Adapter (Adapter-4, Unit 4)
Loads DEP-LIB-001 (EmotionalDNAProfile) + DEP-ENG-016 (PsychRoutingBrief)
into SKILL.md Block B.

Architecture reference:
    CCP_Technical_Architecture.md §4 Adapter Registry v2.0 — Adapter-4
    FR4_Emotional_DNA_Extraction_Tech_Spec.md — V1-V10 variables + CSIP v3
    FR18_Psychological_Routing_Brief_Tech_Spec.md — PsychRoutingBrief Block B
    FR8_TTT_Enforcement_Rule_Tech_Spec.md §Layer 2 — C-08 rhythm whitelist

Block B injection produces:
    1. Appraisal variable constraints (V1-V5 — trigger specificity, coping, agency)
    2. Moral foundation activation directives (V6-V10 — MFQ-2 axes)
    3. CSIP v3 extension parameters (emotion_residency, ceiling/floor, suppression)
    4. Psychological routing brief variables (8 resolved FR18 variables)
    5. Rhythm instructions (ALL carry bypass_c08=True — FR8 C-08 whitelist mandate)

FR8 C-08 Exception (hardcoded in this adapter):
    Spec §Layer 2 §C-08 Contamination Vectors:
    'Sentence Rhythm (pacing, syntax length, punctuation density) generated by the
    Psychological Routing Adapter (adapter-4) is computationally classified as a
    Structural Mechanic. Gate C-08 MUST whitelist rhythm instructions.'
    
    ALL RhythmInstruction objects produced by this adapter have bypass_c08=True.
    This is non-negotiable and must never be set to False by callers.

Payload Masking (from PsychRoutingBrief):
    The payload_masking_instruction from DEP-ENG-016 is injected as a Block B
    constraint string. This is the Trojan Horse structural instruction — it forces
    the generation agent to structure content so its psychological function is
    not detectable by the audience.

ADR-01: coach_id scopes all operations.
FR47:   Receipt written per DEP-ENG-041 schema on successful injection.
M-02:   No TTT hardcoded values (TTT-NN) may appear in any output string.
"""

from __future__ import annotations

from src.ccp.core.receipt_chain import ReceiptChain
from src.ccp.models.adapter_registry_models import (
    AdapterRunResult,
    AdapterSlot,
    BlockBInjection,
    BlockTarget,
    RhythmInstruction,
)
from src.ccp.models.emotional_dna_models import EmotionalDNAProfile
from src.ccp.models.psych_routing_models import PsychRoutingBrief


# ─── Constants ────────────────────────────────────────────────────────────────

AGENT_ADAPTER = "Psych-Routing-Adapter"
STAGE_ADAPTER = "ADAPTER-PSYCH-ROUTING-BLOCK-B"
ADAPTER_SLOT = AdapterSlot.PSYCH_ROUTING


# ─── Appraisal Variable Constraint Builders ───────────────────────────────────

def _build_v1_constraint(profile: EmotionalDNAProfile) -> list[str]:
    """V1 — Trigger Specificity Threshold constraint."""
    v1 = profile.appraisal_variables.v1_trigger_specificity_threshold
    score = v1.score
    if score >= 8:
        level = "HIGH SPECIFICITY"
        guidance = (
            "Ground every claim in concrete, specific situations. "
            "Abstract generalisations will not land — this audience processes "
            "through precise, identifiable moments."
        )
    elif score >= 5:
        level = "MID SPECIFICITY"
        guidance = (
            "Balance concrete examples with broader pattern recognition. "
            "Use specific anchors but connect them to general mechanisms."
        )
    else:
        level = "LOW SPECIFICITY"
        guidance = (
            "This audience processes at the pattern level. Use archetypes "
            "and general principles. Hyper-specific examples may feel alienating."
        )

    return [
        f"CONSTRAINT (V1 — Trigger Specificity, score={score}/10 [{level}]): "
        f"{guidance}"
    ]


def _build_v2_constraint(profile: EmotionalDNAProfile) -> list[str]:
    """V2 — Appraisal Sequence Ordering constraint."""
    v2 = profile.appraisal_variables.v2_appraisal_sequence_ordering
    ordering = v2.type.value if v2.type else "mixed"
    mapping = {
        "mechanism_first": (
            "Lead with the mechanism — explain HOW the wound/trigger works before "
            "invoking the emotional response. Logic precedes feeling for this coach."
        ),
        "moral_verdict_first": (
            "Lead with the moral verdict — name what was wrong or unfair before "
            "explaining the mechanism. Justice-orientation drives the framing."
        ),
        "narrative_first": (
            "Lead with the story — establish the narrative arc before introducing "
            "the analytical insight. Emotional transportation precedes understanding."
        ),
        "coping_first": (
            "Lead with the coping frame — establish that recovery is possible before "
            "engaging the wound. Hope-anchoring must precede the descent."
        ),
        "mixed": (
            "Appraisal sequence is context-dependent — follow the archetype's "
            "natural structural requirements rather than a fixed ordering rule."
        ),
    }
    guidance = mapping.get(ordering, f"Appraisal ordering = {ordering}.")
    return [
        f"CONSTRAINT (V2 — Appraisal Sequence [{ordering}]): {guidance}"
    ]


def _build_v3_constraint(profile: EmotionalDNAProfile) -> list[str]:
    """V3 — Coping Potential Pattern constraint."""
    v3 = profile.appraisal_variables.v3_coping_potential_pattern
    ratio = v3.ratio if v3.ratio is not None else 0.5
    if ratio >= 0.7:
        guidance = (
            "HIGH coping potential ratio — always close with actionable resolution. "
            "This coach's audience expects agency and forward momentum. "
            "Do not leave content in the wound without a clear coping pathway."
        )
    elif ratio >= 0.4:
        guidance = (
            "MODERATE coping potential — balance wound acknowledgement with "
            "resolution. Not every piece needs a full action plan, but "
            "forward movement must be implied."
        )
    else:
        guidance = (
            "LOW coping potential ratio — this coach works in the wound longer "
            "before offering resolution. Do not rush to fix. "
            "Validation and witnessing are the primary function here."
        )

    return [
        f"CONSTRAINT (V3 — Coping Potential, ratio={ratio:.2f}): {guidance}"
    ]


def _build_v4_constraint(profile: EmotionalDNAProfile) -> list[str]:
    """V4 — Norm Compatibility Threshold constraint."""
    v4 = profile.appraisal_variables.v4_norm_compatibility_threshold
    score = v4.score
    if score >= 7:
        guidance = (
            "HIGH norm compatibility — this coach operates within broadly shared "
            "social norms. Content that challenges norms too aggressively will "
            "feel inauthentic and will trigger rejection."
        )
    elif score >= 4:
        guidance = (
            "MID norm compatibility — this coach selectively challenges norms "
            "when the challenge serves a higher principle. Frame challenges "
            "as values-driven rather than rule-breaking."
        )
    else:
        guidance = (
            "LOW norm compatibility — this coach is a legitimate rule-breaker. "
            "Direct norm challenges and contrarian positions are authentic. "
            "Do not soften the edge — it is the point."
        )

    return [
        f"CONSTRAINT (V4 — Norm Compatibility, score={score}/10): {guidance}"
    ]


def _build_v5_constraint(profile: EmotionalDNAProfile) -> list[str]:
    """V5 — Agency Attribution Bias constraint."""
    v5 = profile.appraisal_variables.v5_agency_attribution_bias
    bias = v5.dominant.value if v5.dominant else "individual"
    mapping = {
        "self": (
            "SELF agency bias — frame the root cause as individual psychology and "
            "personal patterns. Do not deflect to systems or institutions "
            "unless the coach explicitly uses systemic framing."
        ),
        "individual": (
            "INDIVIDUAL agency bias — maintain the individual as the locus of change, "
            "while acknowledging that external patterns create the conditions. "
            "Empowerment through personal action is the mechanism."
        ),
        "institutional": (
            "INSTITUTIONAL agency bias — this coach names institutional failures as "
            "legitimate root causes. Do not overplace responsibility on individuals "
            "when the wound has an institutional source."
        ),
        "systemic": (
            "SYSTEMIC agency bias — root causes are located in systemic patterns. "
            "Frame solutions at the systemic level alongside personal positioning "
            "within the system. Individual action is valid but insufficient alone."
        ),
    }
    guidance = mapping.get(bias, f"Agency bias = {bias}.")
    return [f"CONSTRAINT (V5 — Agency Attribution [{bias}]): {guidance}"]


def _build_moral_foundation_constraints(profile: EmotionalDNAProfile) -> list[str]:
    """V6-V10 — MFQ-2 Moral Foundation activation directives.

    Only generates constraints for foundations with score > 6 (active axes)
    to avoid constraint bloat. Foundations scoring ≤ 6 are inactive for this coach.
    """
    constraints: list[str] = []
    mf = profile.moral_foundations
    ACTIVE_THRESHOLD = 0.6  # weight > 0.6 means this foundation is dominant for this coach

    foundation_map = [
        ("V6 — Care/Harm", mf.v6_care_harm,
         "Activate care/harm language — this audience is highly sensitive to "
         "suffering and protection narratives. Lead with who is being harmed."),
        ("V7 — Fairness/Cheating", mf.v7_fairness_cheating,
         "Fairness is a primary moral axis — use procedural and outcome-justice "
         "framing. This audience responds to 'the rules were broken' narratives."),
        ("V8 — Loyalty/Betrayal", mf.v8_loyalty_betrayal,
         "Loyalty is central — frame content around in-group belonging and "
         "betrayal costs. Tribal identity and covenant violations resonate deeply."),
        ("V9 — Authority/Subversion", mf.v9_authority_subversion,
         "Authority legitimacy matters — frame insights as grounded in expertise "
         "and earned credibility. Challenges to authority need strong warrant."),
        ("V10 — Sanctity/Degradation", mf.v10_sanctity_degradation,
         "Purity/sanctity is active — use language that protects what is valued "
         "as sacred. Contamination and defilement metaphors land with force."),
    ]

    for label, foundation_field, guidance in foundation_map:
        weight = getattr(foundation_field, "weight", 0.0) or 0.0
        if weight > ACTIVE_THRESHOLD:
            constraints.append(
                f"CONSTRAINT ({label}, weight={weight:.2f}): {guidance}"
            )

    # V10b liberty (if present)
    liberty_weight = getattr(getattr(mf, "v10b_liberty_oppression", None), "weight", 0.0) or 0.0
    if liberty_weight > ACTIVE_THRESHOLD:
        constraints.append(
            f"CONSTRAINT (V10b — Liberty/Oppression, weight={liberty_weight:.2f}): "
            f"Autonomy and freedom from coercion are primary concerns. "
            f"Frame content around reclaiming sovereignty and resisting constraint."
        )

    return constraints


def _build_csip_constraints(profile: EmotionalDNAProfile) -> list[str]:
    """CSIP v3 — Emotional ceiling/floor and suppression pattern constraints."""
    constraints: list[str] = []
    csip = profile.csip_v3_extensions

    # Emotional ceiling (per topic)
    ceiling_topics = getattr(csip.emotional_ceiling_per_topic, "topic_ceilings", [])
    if ceiling_topics:
        ceilings_str = "; ".join(
            f"{tc.topic}→{tc.max_ttt}" for tc in ceiling_topics[:5] if tc.max_ttt
        )
        if ceilings_str:
            constraints.append(
                f"CONSTRAINT (CSIP v3 — Emotional Ceilings): "
                f"Do not exceed topic emotional ceilings: {ceilings_str}. "
                f"Content above these ceilings triggers defensive shutdown."
            )

    # Emotional floor (per topic)
    floor_topics = getattr(csip.emotional_floor_per_topic, "topic_floors", [])
    if floor_topics:
        floors_str = "; ".join(
            f"{tf.topic}→{tf.min_ttt}" for tf in floor_topics[:5] if tf.min_ttt
        )
        if floors_str:
            constraints.append(
                f"CONSTRAINT (CSIP v3 — Emotional Floors): "
                f"Do not fall below topic emotional floors: {floors_str}. "
                f"Content below these floors reads as hollow to this audience."
            )

    # Suppression patterns
    suppression_patterns = getattr(csip.suppression_patterns, "patterns", [])
    if suppression_patterns:
        emotions_str = "; ".join(
            sp.emotion for sp in suppression_patterns[:5] if sp.emotion
        )
        if emotions_str:
            constraints.append(
                f"CONSTRAINT (CSIP v3 — Suppression Patterns): "
                f"This coach's audience suppresses these emotions: {emotions_str}. "
                f"Do not force emotional expression where suppression is protective."
            )

    # Resolution pattern
    resolution_dominant = getattr(csip.resolution_pattern, "dominant", None)
    if resolution_dominant:
        constraints.append(
            f"CONSTRAINT (CSIP v3 — Resolution Pattern [{resolution_dominant.value}]): "
            f"Structure emotional arc to match this coach's resolution style. "
            f"Do not close with resolution patterns that contradict this baseline."
        )

    return constraints


# ─── Rhythm Instruction Builders ──────────────────────────────────────────────

def _build_rhythm_instructions(
    profile: EmotionalDNAProfile,
    brief: PsychRoutingBrief | None,
) -> list[RhythmInstruction]:
    """Generate rhythm/pacing instructions from emotional DNA and routing brief.

    ALL produced instructions carry bypass_c08=True.
    FR8 §C-08: Rhythm instructions from the Psychological Routing Adapter
    are classified as Structural Mechanics and are WHITELISTED by C-08.

    This is non-negotiable. Never modify bypass_c08 to False on these objects.
    """
    instructions: list[RhythmInstruction] = []

    # V2-driven rhythm: appraisal sequence determines pacing
    v2_ordering = profile.appraisal_variables.v2_appraisal_sequence_ordering.type
    v2_val = v2_ordering.value if v2_ordering else "mixed"
    if v2_val == "mechanism_first":
        instructions.append(RhythmInstruction(
            instruction_text=(
                "RHYTHM (V2-driven): Build sentence rhythm to create analytical momentum — "
                "short declarative sentences to state the mechanism, longer sentences to "
                "unfold the consequence. Punctuation density should increase at the pivot."
            ),
            bypass_c08=True,
            source_variable="V2",
        ))
    elif v2_val == "narrative_first":
        instructions.append(RhythmInstruction(
            instruction_text=(
                "RHYTHM (V2-driven): Open with longer, immersive sentence structures "
                "to build narrative transportation. Transition to shorter, punchier "
                "sentences at the insight reveal. The rhythm mirrors the story arc."
            ),
            bypass_c08=True,
            source_variable="V2",
        ))
    elif v2_val in ("moral_verdict_first", "coping_first"):
        instructions.append(RhythmInstruction(
            instruction_text=(
                "RHYTHM (V2-driven): Open with a short, definitive sentence for the "
                "verdict or coping frame. Let subsequent sentences expand at natural pace. "
                "The opening must land with rhythmic authority — no subordinate clauses."
            ),
            bypass_c08=True,
            source_variable="V2",
        ))

    # V3-driven rhythm: coping ratio drives closing pace
    v3_ratio = profile.appraisal_variables.v3_coping_potential_pattern.ratio or 0.5
    if v3_ratio >= 0.7:
        instructions.append(RhythmInstruction(
            instruction_text=(
                "RHYTHM (V3-driven): Accelerate sentence pace in the closing section — "
                "shorter sentences build momentum toward the action frame. "
                "The rhythm should feel like it is pushing toward resolution."
            ),
            bypass_c08=True,
            source_variable="V3",
        ))

    # Routing brief arousal-driven rhythm
    if brief:
        arousal = brief.psychological_classification.arousal_direction.value
        if arousal == "lowers":
            instructions.append(RhythmInstruction(
                instruction_text=(
                    "RHYTHM (FR18 Arousal Direction — lowers): Reduce sentence rhythm intensity "
                    "progressively through the content. Longer sentences, fewer hard stops, "
                    "softer punctuation. The rhythm decelerates audience arousal."
                ),
                bypass_c08=True,
                source_variable="arousal_direction",
            ))
        elif arousal == "raises":
            instructions.append(RhythmInstruction(
                instruction_text=(
                    "RHYTHM (FR18 Arousal Direction — raises): Increase sentence rhythm intensity "
                    "progressively. Short punchy sentences, more hard stops, higher punctuation "
                    "density toward the close. The rhythm elevates audience arousal."
                ),
                bypass_c08=True,
                source_variable="arousal_direction",
            ))

    return instructions


# ─── Block B Constraint Builder ───────────────────────────────────────────────

def _build_routing_brief_constraints(brief: PsychRoutingBrief) -> list[str]:
    """Build Block B constraint strings from DEP-ENG-016 PsychRoutingBrief variables."""
    pc = brief.psychological_classification
    constraints: list[str] = [
        f"PSYCH ROUTING (FR18 DEP-ENG-016 — routing_id={brief.routing_id}):",
        f"CONSTRAINT: mood_state_primary = <{pc.mood_state_primary.value}>. "
        f"Structure the content's emotional purpose to serve this primary need.",
        f"CONSTRAINT: arousal_direction = <{pc.arousal_direction.value}>. "
        f"The content must move the audience's arousal in this direction.",
        f"CONSTRAINT: valence_delivery = <{pc.valence_delivery.value}>. "
        f"Emotional atmosphere must match this polarity.",
        f"CONSTRAINT: regulatory_frame = <{pc.regulatory_frame.value}>. "
        f"Frame outcomes through this regulatory lens (promotion vs prevention).",
        f"CONSTRAINT: sdt_need_primary = <{pc.sdt_need_primary.value}>. "
        f"The content's core psychological function must satisfy this SDT need.",
    ]

    if pc.sequencing_dependency.value != "independent":
        constraints.append(
            f"CONSTRAINT: sequencing_dependency = <{pc.sequencing_dependency.value}>. "
            f"This content requires positive affect priming before deployment."
        )

    if pc.comparison_type.value != "none":
        constraints.append(
            f"CONSTRAINT: comparison_type = <{pc.comparison_type.value}>. "
            f"Social comparison mechanics must be structured to this type."
        )

    if pc.tmt_function.value != "none":
        constraints.append(
            f"CONSTRAINT: tmt_function = <{pc.tmt_function.value}>. "
            f"Terror Management Theory function — must match worldview engagement type."
        )

    # Payload masking instruction (Trojan Horse structural behaviour)
    if brief.payload_masking_instruction:
        constraints.append(
            f"PAYLOAD MASKING (FR18 Trojan Horse): {brief.payload_masking_instruction}"
        )

    if brief.is_fallback and brief.operator_warning:
        constraints.append(
            f"[OPERATOR WARNING — FALLBACK BRIEF]: {brief.operator_warning}"
        )

    return constraints


# ─── Adapter ─────────────────────────────────────────────────────────────────

class PsychRoutingAdapter:
    """Adapter-4 — Loads DEP-LIB-001 + DEP-ENG-016 into SKILL.md Block B.

    Injects:
        - V1-V5 appraisal variable constraints
        - V6-V10 MFQ-2 moral foundation directives
        - CSIP v3 ceiling/floor/suppression constraints
        - PsychRoutingBrief (DEP-ENG-016) 8-variable resolved routing block
        - Rhythm instructions (ALL bypass_c08=True — FR8 C-08 whitelist mandate)

    The routing brief (DEP-ENG-016) is optional — if not provided, only
    emotional DNA constraints are injected (no routing brief warnings).

    ADR-01: coach_id in all outputs and receipt logs.
    C-08 MANDATE: All RhythmInstruction objects carry bypass_c08=True. This is
        structural law from FR8 and cannot be overridden by callers.
    """

    def __init__(self, receipt_chain: ReceiptChain) -> None:
        self._rc = receipt_chain

    def load(
        self,
        emotional_dna: EmotionalDNAProfile,
        coach_id: str,
        routing_brief: PsychRoutingBrief | None = None,
    ) -> AdapterRunResult:
        """Execute the Emotional DNA + Routing Brief → Block B injection.

        Args:
            emotional_dna: Validated DEP-LIB-001 EmotionalDNAProfile.
            coach_id: ADR-01 coach instance identifier.
            routing_brief: Optional DEP-ENG-016 PsychRoutingBrief. If provided,
                adds 8-variable routing constraints and payload masking instruction.

        Returns:
            AdapterRunResult with Block B injection payload on success.
        """
        constraints: list[str] = []

        # ── V1-V5 Appraisal Variable Constraints ──────────────────────────────
        constraints.extend(_build_v1_constraint(emotional_dna))
        constraints.extend(_build_v2_constraint(emotional_dna))
        constraints.extend(_build_v3_constraint(emotional_dna))
        constraints.extend(_build_v4_constraint(emotional_dna))
        constraints.extend(_build_v5_constraint(emotional_dna))

        # ── V6-V10 Moral Foundation Directives ────────────────────────────────
        moral_constraints = _build_moral_foundation_constraints(emotional_dna)
        constraints.extend(moral_constraints)

        # ── CSIP v3 Extension Constraints ─────────────────────────────────────
        csip_constraints = _build_csip_constraints(emotional_dna)
        constraints.extend(csip_constraints)

        # ── Routing Brief Constraints (if provided) ────────────────────────────
        if routing_brief:
            constraints.extend(_build_routing_brief_constraints(routing_brief))

        # ── Rhythm Instructions (ALL bypass_c08=True) ─────────────────────────
        rhythm_instructions = _build_rhythm_instructions(emotional_dna, routing_brief)

        # ── Assemble injection ─────────────────────────────────────────────────
        injection = BlockBInjection(
            adapter_slot=ADAPTER_SLOT,
            coach_id=coach_id,
            target=BlockTarget.BLOCK_B,
            section_header="## Psychological Routing Constraints (Adapter-4 — DEP-LIB-001 + DEP-ENG-016)",
            constraint_strings=constraints,
            rhythm_instructions=rhythm_instructions,
            metadata={
                "dep_lib_001": "DEP-LIB-001",
                "dep_eng_016": routing_brief.routing_id if routing_brief else None,
                "has_routing_brief": routing_brief is not None,
                "constraint_count": len(constraints),
                "rhythm_instruction_count": len(rhythm_instructions),
                "all_rhythm_bypass_c08": all(r.bypass_c08 for r in rhythm_instructions),
                "emotional_dna_confidence": getattr(
                    getattr(emotional_dna, "extraction_status", None),
                    "confidence",
                    None,
                ),
            },
        )

        # ── Receipt Write (FR47 DEP-ENG-041) ──────────────────────────────────
        entry = self._rc.log(
            agent_id=AGENT_ADAPTER,
            action=STAGE_ADAPTER,
            input_summary=(
                f"coach_id={coach_id} "
                f"routing_brief={'present' if routing_brief else 'absent'} "
                f"dep_lib_001_confidence="
                f"{getattr(getattr(emotional_dna, 'extraction_status', None), 'confidence', 'N/A')}"
            ),
            output_summary=(
                f"Block_B_constraints={len(constraints)} "
                f"rhythm_instructions={len(rhythm_instructions)} "
                f"all_bypass_c08={all(r.bypass_c08 for r in rhythm_instructions)}"
            ),
            metadata={
                "stage_name": STAGE_ADAPTER,
                "adapter_slot": ADAPTER_SLOT.value,
                "coach_id": coach_id,
                "dep_lib_001": "DEP-LIB-001",
                "has_routing_brief": routing_brief is not None,
                "constraint_count": len(constraints),
                "rhythm_instruction_count": len(rhythm_instructions),
                "c08_rhythm_whitelist_status": "ALL_WHITELISTED",
            },
        )

        return AdapterRunResult(
            adapter_slot=ADAPTER_SLOT,
            coach_id=coach_id,
            success=True,
            block_b=injection,
            receipt_id=entry.receipt_id,
            gate_failures=[],
            warnings=[],
        )

    def format_block_b_section(
        self,
        emotional_dna: EmotionalDNAProfile,
        coach_id: str,
        routing_brief: PsychRoutingBrief | None = None,
    ) -> str:
        """Produce the full Block B section text for SKILL.md injection.

        Returns:
            Multi-line string ready for SKILL.md Block B injection.
        """
        result = self.load(emotional_dna, coach_id, routing_brief)
        if result.block_b:
            return result.block_b.to_block_b_text()
        return ""
