-- USER PROGRAMS TABLE
-- Stores the 30-day schedule generated by Atlas
CREATE TABLE IF NOT EXISTS user_programs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL CHECK (day_number >= 1 AND day_number <= 30),
    ritual_id UUID REFERENCES rituals(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- DAILY JOURNALS TABLE
-- Stores the user's voice notes and the system's analysis
CREATE TABLE IF NOT EXISTS daily_journals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    audio_url TEXT, -- Path in Supabase Storage
    transcript TEXT,
    sentiment_score FLOAT, -- -1.0 to 1.0
    entities JSONB, -- Extracted entities (Context Premise updates)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PAYMENTS TABLE
-- Stores transaction history from Stripe
CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    amount_cents INTEGER NOT NULL,
    stripe_transaction_id TEXT UNIQUE,
    status TEXT DEFAULT 'succeeded',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS POLICIES
ALTER TABLE user_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Service Role Access (Simplified for MVP)
CREATE POLICY "Allow Service Role full access to user_programs" ON user_programs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Service Role full access to daily_journals" ON daily_journals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Service Role full access to payments" ON payments FOR ALL USING (true) WITH CHECK (true);
